### PR TITLE
Test adding GitHub Actions CI to PRs

### PR DESCRIPTION
**Pull request by bshapiroalbert**
Testing if GitHub Actions CI is at least working in my own local Repo.

### CODE REVIEW

**Comment by Hazboun6** [comment]
Looks like the error in the `Py3.6` build is the same as on Travis... 😢

**Comment by bshapiroalbert** [comment]
> Looks like the error in the `Py3.6` build is the same as on Travis... 😢

@Hazboun6 yeah, it's the same issue. If I remove 3.6 then 3.7 and 3.8 both pass, but I'm not sure what the best thing to do with is moving forward is for now. Maybe we can discuss more.

**Comment by Hazboun6** [comment]
@bshapiroalbert , wait that's progress! In this [Travis build](https://travis-ci.org/github/PsrSigSim/PsrSigSim/builds/750595654) none of them passed.

**Comment by bshapiroalbert** [comment]
> @bshapiroalbert , wait that's progress! In this [Travis build](https://travis-ci.org/github/PsrSigSim/PsrSigSim/builds/750595654) none of them passed.

I think the only reason that these fail after the 3.6 test fails is because the next tests try to use cached versions of the packages from the 3.6 tests, and then when they get to the `fitsio` test they cancel because it didn't every compile in the 3.6 tests. I wonder if something similar is happening in the Travis tests? Either way these test run WAY faster.

**Comment by bshapiroalbert** [comment]
Everything seems to be passing now, Woo!

**Comment by Hazboun6** [comment]
@bshapiroalbert what was the fix here to get the Py3.6 tests to pass?

**Comment by bshapiroalbert** [comment]
@Hazboun6 all I ended up dong o make it pass the 3.6 tests, was in the
`python -m pip install --upgrade pip`
line, I just also added setuptool and wheel to the end,
`python -m pip install --upgrade pip setuptools wheel`
So maybe that would have worked for Travis too, but who knows.

**Pull request merged**
